apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - powerdns-postgres.yaml
  - powerdns-auth.yaml
  - auth-dns-service.yaml
  - auth-web-service.yaml
  - jinja-templates.yaml
  - pdns-ingress.yaml
  # - powerdns-admin.yaml
  # - powerdns-admin-configmap.yaml
